---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-hostpath-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/opt/kubernetes-storage/nginx"
