---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-hostpath-volumeclaim
spec:
  storageClassName: nginx-manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
